### ISSUE TITLE
Display data name (Update)

### ISSUE THREAD

**Issue by Qisheng-Tang** [computationalmystic/augur-group25#6]
**Is your feature request related to a problem? If so, please describe the problem:**
The x-axis does not show the data name which retrieved from API

**Describe the solution you'd like:**
Make the axis display the data name.
We will try to modify the .vue file in order to achieve the function.

![IMG_0004](https://user-images.githubusercontent.com/39931310/56871613-165b7d80-69e6-11e9-92d6-6be7e9d391a0.PNG)

**Comment by Arianardo** [comment]
We were able to fix the lines changed per week and month graphs so that different dates are shown across the x axis chronologically.  This helped correctly display the line chart.  Commits per week is still a work in progress.  After fixing this on the other graphs the commits per week is now blank and its date field is undefined.

**Comment by Arianardo** [comment]
Commits per week is up but still not displaying correctly.

**Comment by Arianardo** [comment]
All graphs are up and their axes display correctly.

**Comment by ghost** [comment]
The issue was faced was that the graph was not being passed valid data that was retrieved from the API. We came up with a solution to manually pass the API's variables so that the graph will be updated accordingly with the correct metrics.
<img width="742" alt="Screen Shot 2019-05-04 at 7 54 27 PM" src="https://user-images.githubusercontent.com/47017176/57187088-7acb8080-6eaf-11e9-86b5-4248476daa06.png">

**Comment by ghost** [comment]
This issue was assigned to all three of our graph members. We worked together to determine the variables retrieved by the API.

**Comment by ghost** [comment]
This change was effective once the API data was modified to accept the newly formatted "date." This resulted in the graph having the correct variables AND it being able to accept the API data. This was the final step in fixing out graphs so they display correctly, this is an example of how it works now:
<img width="640" alt="Screen Shot 2019-05-05 at 9 12 35 PM" src="https://user-images.githubusercontent.com/47017176/57204041-88017180-6f7a-11e9-8ff6-e1ff464474f6.png">
